[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About"
  identifier = "about"
  pageRef = "/about"
  weight = 20

[[main]]
  name = "Vision & goals"
  pageRef = "/about"
  parent = "about"
  weight = 20

[[main]]
  name = "Current work"
  pageRef = "/wip"
  parent = "about"
  weight = 21

[[main]]
  name = "Open tools"
  pageRef = "/toolbox"
  parent = "about"
  weight = 22

[[main]]
  name = "Missions"
  pageRef = "/projects"
  weight = 30

[[main]]
  name = "Network"
  identifier = "network"
  pageRef = "/members"
  weight = 40

[[main]]
  name = "Members"
  pageRef = "/members"
  parent = "network"
  weight = 30

[[main]]
  name = "Join the network"
  pageRef = "/join"
  parent = "network"
  weight = 31

[[main]]
  name = "News"
  pageRef = "/posts"
  weight = 50

[[main]]
  name = "Support EMI"
  pageRef = "/support"
  weight = 60

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://www.linkedin.com/company/earth-metabolome-initiative/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/earth-metabolome-initiative"
  weight = 20

[[social]]
  name = "Mastodon"
  pre = "fab mastodon"
  url = "https://mastodon.social/@earth_metabolome"
  weight = 30
